- name: reload agate
  ansible.builtin.systemd:
    name: agate.service
    state: restarted
    daemon_reload: yes

- name: reload rsyslogd
  ansible.builtin.systemd:
    name: rsyslogd.service
    state: reloaded